version: '3'

services:
  web:
    container_name: htmx_demo_web
    build: .
    # command: flask run -h 0.0.0.0 -p 5000 --with-threads
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
    volumes:
      - .:/usr/src/app
